version: '3'

services:
  check-certs:
    build:
      context: ./
      dockerfile: Dockerfile
    image: check-certs
    container_name: check-certs
    restart: always
    network_mode: host
    volumes:
    - ./config.yaml:/tmp/config.yaml:ro
    - /etc/localtime:/etc/localtime:ro
    command: /check-certs --config=/tmp/config.yaml